version: '3'

services:
  database:
    container_name: cosmobots-postgres-db
    image: postgres:12.3
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
